fix post-processing interpreter to try python3 before attempting python, which might point to python2, python3 or not exist, depending on distro implementation and if python2 is present.

diff --git a/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml b/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml
--- a/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml
+++ b/aws-tpcc-tde-medium-amd/03_execute/playbook-tpcc-run.yml
@@ -255,7 +255,16 @@
     # worry about whether all the files exists for the push_results steps, meaning
     # we don't have to hack that for the time being.
     - name: Generate final data points and chart
-      ansible.builtin.shell: python3 {{ playbook_dir }}/post-processing.py || echo "ignoring errors"
+      ansible.builtin.command:
+        cmd: |
+          # Some distros use python for python3 since python2 is EOL
+          if command -v python3
+          then
+            PLAYBOOK_PYTHON="python3"
+          else
+            PLAYBOOK_PYTHON="python"
+          fi
+          $PLAYBOOK_PYTHON {{ playbook_dir }}/post-processing.py || echo "ignoring errors"
 
     - name: Move data to results directory
       ansible.builtin.copy:
